spring:
  application:
    name: uri2990

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/uri
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # pode ser create, create-drop, validate, etc.
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  server:
    port: 8080

