spring:
  application:
    name: login_acesso

  profiles:
    active: test

  output:
    ansi:
      enabled: ALWAYS

#  cors:
#    origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}


logging:
  pattern:
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}
      %clr(%-5p)
      %clr([%t]){cyan}
      %clr(%-50.50logger{0}){blue}
      %clr(:){yellow}
      %m

---

# TEST (profile test)
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:login
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true