spring:
  application:
    name: login_acesso

  profiles:
    active: test

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}
      %clr(%-5p)
      %clr([%t]){cyan}
      %clr(%-50.50logger{0}){blue}
      %clr(:){yellow}
      %m
---

spring:
  config:
    activate:
      on-profile: test

  #security:
  #  client-id: myclientid
  #  client-secret: myclientsecret
  #  jwt:
  #    duration: 86400
  #
  #cors:
  #  origins: http://localhost:3000,http://localhost:5173
  #
  # USEI VARIAVEIS DE AMBIENTE DIRETAMENTE NO INTELLIJ.

security:
  client-id: ${SECURITY_CLIENT_ID}
  client-secret: ${SECURITY_CLIENT_SECRET}
  jwt:
    duration: ${SECURITY_JWT_DURATION}
  cors:
    origins: ${CORS_ORIGINS}


  datasource:
    url: jdbc:h2:mem:login
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true