version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: sql_study_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql_study
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sql-study-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sql_study_pgadmin
    restart: always
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - sql-study-network

networks:
  sql-study-network:
    driver: bridge

volumes:
  postgres_data:
